language: node_js
node_js:
  - "stable"
install:
  - npm i
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE todo_test;" -U postgres
  
script:
  - npm run migrate
  - npm test
after_success:
  - npm run coverage
notifications:
  email: false
sudo: false